### ISSUE TITLE
File input label displaying over the top of the Select button

### ISSUE THREAD

**Issue by cliveportman** [hperrin/svelte-material-ui#160]
When NOT in focus, the label sits over the top of the file select button in the demo. This is Chrome on Windows.
It's just missing the `mdc-floating-label--float-above` class.

**Comment by danielcaldas** [comment]
I'm facing the same issue after upgrading to `v4.1.0`. For now, the workaround I'm using is to override the faulty `.mdc-floating-label` with the `transform` that fixes the floating label.

```css
  :global(.mdc-select__anchor .mdc-floating-label) {
    transform: translateY(-106%) scale(0.75) !important;
  }
```
