### ISSUE TITLE
textarea resize handle looks bad on firefox when using a dark theme

### ISSUE THREAD

**Issue by rebootl** [hperrin/svelte-material-ui#201]
![image](https://user-images.githubusercontent.com/3398507/105610110-1dc3dc80-5dae-11eb-8cbe-7655f5a14f03.png)

See image.

```css
:global(.mdc-notched-outline__trailing) {
    background-color: var(--main-background-color);
  }
```

I could override the background-color like this, but then the handle, isn't visible at all. Not sure why.
In a regular textarea element it looks fine.

![image](https://user-images.githubusercontent.com/3398507/105610788-bc057180-5db1-11eb-9463-c0482a9f486a.png)

If possible to fix, would be great.
Thx.
