### ISSUE TITLE
Sass step of installation unclear

### ISSUE THREAD

**Issue by wfehrnstrom** [hperrin/svelte-material-ui#23]
I was wondering if you could clarify the sass configuration step for installing this package. You specify not to use a sass-svelte-preprocessor, and I believe this is because what is really needed here is to process the sass files within svelte-material-ui, not the user's code base. What are the steps for processing the .scss files within your library? Using sass on the whole directory via cli is not an option because of the _ prefix on all the .scss files. Trying to process them individually is also a bust, as errors are thrown. I apologize for my naivete.

**Comment by wfehrnstrom** [comment]
After adding a preprocessing step as part of my rollup configuration, the sass is now being parsed correctly. However I am still unclear on the smui-theme step of the process. Reason being that in your internal code, you import smui-theme, but in your demo that you direct people to to see an example of smui-theme in action, you have a file _smui-theme.scss, which contains material ui styling themes. Could you elaborate on your process for this step

**Comment by hperrin** [comment]
Yeah. Basically that file let's you specify all the theming variables before the MDC Sass files are imported. That way the components can include the styling, while still letting you set those variables.

**Comment by hperrin** [comment]
If you want to include the Sass yourself, you can also do that and include the Svelte files by name.

**Comment by hperrin** [comment]
(since the index.js file is what includes the Sass)

**Comment by ramaisen** [comment]
> After adding a preprocessing step as part of my rollup configuration, the sass is now being parsed correctly. However I am still unclear on the smui-theme step of the process. Reason being that in your internal code, you import smui-theme, but in your demo that you direct people to to see an example of smui-theme in action, you have a file _smui-theme.scss, which contains material ui styling themes. Could you elaborate on your process for this step

Can you provide your configuration of rollup? Im haveing trouble making it work

**Comment by hengnee** [comment]
I got the rollup configuration working but my buttons' ripple effect does not seem to work.
Upon looking into the packages, it seems to be using @material packages. 
Do I have to include them in my node_modules seperately or am I missing something here?

**Comment by hengnee** [comment]
> @hengnee, you shouldn't need to include them yourself. Can you share a link to your config and I'll take a look?

May I add you into my repo for you to take a look at it?
I have not set my repo to public yet and so I won't be able to share it here

**Comment by hperrin** [comment]
@hengnee I'm not sure what the problem is. I haven't used Tailwind before, so I'm a bit in the dark.

**Comment by hengnee** [comment]
> @hengnee I'm not sure what the problem is. I haven't used Tailwind before, so I'm a bit in the dark.

No worries, I will find a solution for it somehow.
Btw, thank you so very much for this library! It's really a rare gem to have for Svelte project!

**Comment by hperrin** [comment]
@hengnee Thanks for the kind words. I'm really glad that it's useful to so many fellow Svelte devs. :D

**Comment by hengnee** [comment]
Hi future readers,

I am leaving my setup of the rollup.config.js in this comment as well as other parts of the configuration that may help in the setting up of this Material UI library for your own use.

I've personally met the problem where I have had set up the smui library but the CSS had clashed with the CSS defaults of Tailwind CSS within the "@tailwind/base".

I had to add the CSS code back in to remove the problems. E.g. All ripple effects were not present.

Hope this comment serves to help anyone facing the same problems! Cheers!

`
@import "tailwindcss/base";
@import "tailwindcss/components";
@import "tailwindcss/utilities";
*,
*::before,
*::after {
  border-width: unset;
  border-style: unset;
  border-color: unset;
}
button:focus {
  outline: unset;
  outline: unset;
}
img {
  border-style: none;
}
`


**rollup.config.js**
`
import svelte         from "rollup-plugin-svelte";
import resolve        from "rollup-plugin-node-resolve";
import commonjs       from "rollup-plugin-commonjs";
import livereload     from "rollup-plugin-livereload";
import postcss        from "rollup-plugin-postcss";
import autoPreprocess from "svelte-preprocess";
import {terser}       from "rollup-plugin-terser";

const production = !process.env.ROLLUP_WATCH;

export default {
  input: "src/main.js",
  output: {
    sourcemap: !0,
    format: "iife",
    name: "app",
    file: "public/bundle.js"
  },
  plugins: [
    postcss({
      extract: "public/material.css",
      minimize: production,
      use: [
        ["sass", {
          includePaths: [
            // styles folder contains the necessary "_smui-theme.scss" file.
            "./src/styles",
            "./node_modules",
          ]
        }]
      ],
    }),
    svelte({
      preprocess: autoPreprocess({ postcss: true }),
      dev: !production,
      css: css => css.write("public/bundle.css"),
      //! The emnitCss portion was the one the created the problem of other
      //! "global" CSS files being written with Svelte CSSes.
      emitCss: !!0
    }),
    resolve({
      browser: true,
      dedupe: importee =>
        importee === "svelte" || 
        importee.startsWith("svelte/")
    }),
    commonjs(),
    !production && livereload("public"),
    production && terser()
  ],
  watch: { clearScreen: !0 }
};
`
**_smui-theme.scss**
_Note that you may leave this blank if you just want to use the smui defualts._
`
/**//* Import Material UI color themes */
@import "@material/theme/color-palette";
/**//* Import Material defualt typography */
@import "@material/typography/mdc-typography";
/**//* Theming of the Svelte Material UI components */
$mdc-theme-primary                     : transparent;
$mdc-theme-secondary                   : teal;
$mdc-theme-background                  : $material-color-grey-900;
$mdc-theme-surface                     : $material-color-grey-100;
$mdc-theme-error                       : $material-color-red-900;
$mdc-theme-on-primary                  : $material-color-grey-800;
$mdc-theme-on-secondary                : black;
$mdc-theme-on-surface                  : $material-color-grey-800;
$mdc-theme-on-error                    : black;
$mdc-theme-text-primary-on-background  : white;
$mdc-theme-text-secondary-on-background: hsla(0,0%,100%,0.7);
$mdc-theme-text-hint-on-background     : hsla(0,0%,100%,0.5);
$mdc-theme-text-disabled-on-background : hsla(0,0%,100%,0.5);
$mdc-theme-text-icon-on-background     : hsla(0,0%,100%,0.5);
$mdc-theme-text-primary-on-light       : rgba(0,0,0,0.87);
$mdc-theme-text-secondary-on-light     : rgba(0,0,0,0.54);
$mdc-theme-text-hint-on-light          : rgba(0,0,0,0.38);
$mdc-theme-text-disabled-on-light      : rgba(0,0,0,0.38);
$mdc-theme-text-icon-on-light          : rgba(0,0,0,0.38);
$mdc-theme-text-primary-on-dark        : white;
$mdc-theme-text-secondary-on-dark      : hsla(0,0%,100%,0.7);
$mdc-theme-text-hint-on-dark           : hsla(0,0%,100%,0.5);
$mdc-theme-text-disabled-on-dark       : hsla(0,0%,100%,0.5);
$mdc-theme-text-icon-on-dark           : hsla(0,0%,100%,0.5);
`

**Comment by mtwichel** [comment]
@hengnee I am having similar issues with conflicts with the materials ripple: "Error: 'MDCRipple' is not exported by node_modules/@material/ripple/dist/mdc.ripple.js"

My question is, how did you find that you had a conflict with @tailwind? I don't have that package specifically, but I bet I do have a conflict somewhere. I just can't find where.

Thanks!

**Comment by cdock1029** [comment]
@hengnee I've tried to customize theme variables as well... but how do you get the background color (`$mdc-theme-background` to show up, is there a class to add in your html/markup?

All I'm seeing is primary/secondary color changes but not backgrounds or text changes...

**Comment by AnthyG** [comment]
@cdock1029 you could either just set it with `background: $mdc-theme-background;` or

```scss
@import "@material/theme/mixins";

$mdc-theme-background: #000;

@import "@material/theme/variables";
@each $style in map-keys($mdc-theme-property-values) {
	--mdc-theme-#{$style}: #{map-get($mdc-theme-property-values, $style)};
}

html body {
	@include mdc-theme-prop(
		background,
		(
			varname: --mdc-theme-background,
			fallback: $mdc-theme-background	)
	);
}
```

(lol, I hope that actually works, as I can't really see through all the weird stuff that I did to get [this] (https://codepen.io/anthyG/pen/PowroMV) working with Svelte and Svelte Material UI anymore (and my current setup is probably really sh*t, because it's generating 4.5 **MB** or even **10 MB** (I think it's just the same as the 4.5 MB version but cloned content, maybe because it's importing it twice,... somehow :woman_shrugging:) CSS files (takes about 2 minutes to build everytime), and I've tried like so much)).

You might also want to take a look at [/site/src/routes/demo/theme.scss](https://github.com/hperrin/svelte-material-ui/blob/master/site/src/routes/demo/theme.scss) if you haven't already (the result of which is visible here: https://sveltematerialui.com/demo/theme).

Just as a note, I also use the same background-color for `$mdc-theme-surface`, so the previous piece now looks like follows:

```scss
@import "@material/theme/mixins";

$mdc-theme-background: #000;
$mdc-theme-surface: $mdc-theme-background;
$mdc-theme-on-surface: if(
	mdc-theme-contrast-tone($mdc-theme-surface) == "dark",
	#000,
	#fff
);

@import "@material/theme/variables";
@each $style in map-keys($mdc-theme-property-values) {
	--mdc-theme-#{$style}: #{map-get($mdc-theme-property-values, $style)};
}

// and then probably also import all the used SMUI component styles, e.g.
@import "@smui/switch/style";


html body {
	@include mdc-theme-prop(
		color,
		(
			varname: --mdc-theme-on-surface,
			fallback: $mdc-theme-on-surface
		)
	);
	@include mdc-theme-prop(
		background,
		(
			varname: --mdc-theme-background,
			fallback: $mdc-theme-background	)
	);
}
```

If you want to see the chaos I created, tell me, I'll put it somewhere. xD
