### ISSUE TITLE
Adding Tailwind adds border inside focused Textfield elements

### ISSUE THREAD

**Issue by JohanHeyvaert** [hperrin/svelte-material-ui#539]
**Describe the bug**
After adding Tailwind to the project (SvelteKit + smui) the TextFields get two inside vertical borders when focused.
These vertical borders are not shown when the textfield is not focused.

**To Reproduce**
1. Add Tailwind to a SvelteKit project that uses smui Textfield by following these instructions: https://tailwindcss.com/docs/guides/sveltekit
2. Now focus a Textfield and the problem appears

**Expected behavior**
The vertical borders inside the input should not be shown.

**Screenshots**
Cf. screenshot:
![image](https://user-images.githubusercontent.com/13747250/203542856-6f589bef-1bde-4fec-8cd2-65b21845a96c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 107

I was able to solve the problem by adding this style to my general css file:

``` css
/* Fix: smui + tailwind adds left & right borders within textfields */
.mdc-text-field--outlined .mdc-notched-outline--notched .mdc-notched-outline__notch {
    border-left: 0;
    border-right: 0;
}
```
