### ISSUE TITLE
Issue with @smui/snackbar

### ISSUE THREAD

**Issue by varghesethomase** [hperrin/svelte-material-ui#574]
**Describe the bug**
As multiple people face the same issue as shown in the[ stack overflow thread](https://stackoverflow.com/questions/73167345/svelte-material-ui-colored-snackbar), it seems like the example given [here](https://sveltematerialui.com/demo/snackbar/) on how to have multiple variants of the snackbar eg: success, error and warning is broken. 
As shown in the figure below, on trying to compile sass, it errors.
<img width="680" alt="image" src="https://user-images.githubusercontent.com/5429756/221501752-1847e6a3-1767-43d4-9d23-cfefca3acebb.png">

**To Reproduce**
1. Go to the _smui_theme.scss file
2. Add the following:
```
@use '@material/snackbar/index' as snackabar;

.mdc-snackbar.snackbar--success {
  @include snackabar.fill-color(color-palette.$green-900);
  @include snackabar.label-ink-color(theme.accessible-ink-color(color-palette.$green-900));
}

.mdc-snackbar.snackbar--warning {
  @include snackabar.fill-color(color-palette.$orange-900);
  @include snackabar.label-ink-color(theme.accessible-ink-color(color-palette.$orange-900));
}

.mdc-snackbar.snackbar--error {
  @include snackabar.fill-color(color-palette.$red-900);
  @include snackabar.label-ink-color(theme.accessible-ink-color(color-palette.$red-900));
}
```
4. Compile using `npm run smui-theme`
5. See  the error

**Expected behavior**
The error is not shown but the scss compiles

**Screenshots**
<img width="894" alt="image" src="https://user-images.githubusercontent.com/5429756/221502827-7478b509-9363-4be1-9540-c937c1754dab.png">

**Desktop (please complete the following information):**
 - OS: [MacOS]

**Comment by drewsilcock** [comment]
Here's my workaround that bypasses the nice Snackbar mixins and just hardcodes the colours:

```scss
.mdc-snackbar.snackbar--success .mdc-snackbar__surface {
  background-color: color-palette.$green-500;
}

.mdc-snackbar.snackbar--success .mdc-snackbar__surface .mdc-snackbar__label,
.mdc-snackbar.snackbar--success .mdc-snackbar__surface .mdc-snackbar__actions .mdc-snackbar__dismiss {
  color: black;
}

.mdc-snackbar.snackbar--warning .mdc-snackbar__surface {
  background-color: color-palette.$orange-500;
}

.mdc-snackbar.snackbar--warning .mdc-snackbar__surface .mdc-snackbar__label,
.mdc-snackbar.snackbar--warning .mdc-snackbar__surface .mdc-snackbar__actions .mdc-snackbar__dismiss {
  color: black;
}

.mdc-snackbar.snackbar--error .mdc-snackbar__surface {
  background-color: color-palette.$red-500;
}

.mdc-snackbar.snackbar--error .mdc-snackbar__surface .mdc-snackbar__label,
.mdc-snackbar.snackbar--error .mdc-snackbar__surface .mdc-snackbar__actions .mdc-snackbar__dismiss {
  color: white;
}
```
