### ISSUE TITLE
Parcel: can't find stylesheet to import: @import "smui-theme";  

### ISSUE THREAD

**Issue by thomanimation** [hperrin/svelte-material-ui#87]
I've tried several approaches to get svelte-material-ui to work with parcel but I can't figure out how to set up the _smui-theme.scss correctly. I get the following error as a result:
```
node_modules/@smui/button/_index.scss:1:9: Can't find stylesheet to import.
  ╷
1 │ @import "smui-theme";
  ╵
  node_modules/@smui/button/_index.scss 1:9  root stylesheet
Error: Can't find stylesheet to import.
```

In my project there are 3 folders: node_modules, src and themes.
The themes folder contains a _smui-theme.scss file.

My postcss.config.js file looks like this:

```
const plugins =
  process.env.NODE_ENV === 'production'
    ? ['tailwindcss', 'autoprefixer', '@fullhuman/postcss-purgecss']
    : ['tailwindcss'];

module.exports = {
  plugins,
  use: [ [
          "sass",
          {
              includePaths: ["./themes", "./node_modules"]
          }
        ] ]
}
```

**Comment by devghost** [comment]
Not ideal, but I got it working by importing the specific js & styles explicitly...

HTH

```
<script>
    import TopAppBar, {Row, Section, Title} from '@smui/top-app-bar/bare.js';
    import '@smui/top-app-bar/bare.css';

    import IconButton from '@smui/icon-button/bare.js';
    import '@smui/icon-button/bare.css';
</script>

```

**Comment by andy37380** [comment]
try follow steps：

# install rollup-plugin-postcss
`
npm install rollup-plugin-postcss
`

# edit rollup.config.js
```
export default {
    // Omitted.....
    plugins: [
        // Omitted.....
        // **add postcss settings**
        postcss({
            extensions: ['.scss', '.sass'],
            extract: false,
            minimize: true,
            use: [
                ['sass', {
                    includePaths: [
                        './src/theme',
                        './node_modules'
                    ]
                }]
            ]
        }),
        // Omitted.....
    ]
};
```

# add empty file
src\\theme\\_smui-theme.scss

**Comment by thomanimation** [comment]
Thank you. I'm looking for a way to get it working with Parcel instead of rollup.

**Comment by cdock1029** [comment]
A workaround, as per @devghost suggestion, you can use the bare imports.

Customized theme can be achieved by placing this in an `.scss` file imported into your html:

```scss
@import '@material/theme/color-palette';

$mdc-theme-primary: $material-color-indigo-800;
$mdc-theme-secondary: $material-color-red-a700;

$mdc-theme-background: $material-color-grey-400;
$mdc-theme-surface: #fff;

$mdc-theme-error: $material-color-red-900;

@import '@material/typography/mdc-typography';
// This adds classes like "mdc-theme--primary-bg".
@import '@material/theme/mdc-theme';

body {
  background: $mdc-theme-background;
}

// can add this to style typography automatically
html {
  @include mdc-typography('body1');
}
h1 {
  @include mdc-typography('headline1');
}

h2 {
  @include mdc-typography('headline2');
}

h3 {
  @include mdc-typography('headline3');
}

h4 {
  @include mdc-typography('headline4');
}

h5 {
  @include mdc-typography('headline5');
}

h6 {
  @include mdc-typography('headline6');
}

caption {
  @include mdc-typography('caption');
}

code,
pre {
  font-family: 'Roboto Mono', monospace;
}

small {
  font-size: 0.9em;
}

big {
  font-size: 1.1em;
}

b,
strong {
  font-weight: bold;
}
```
